workspace:
    base: /go
    path: src/github.com/SierraSoftworks/sentry-go

pipeline:
    go:get:
        image: golang:1.9
        commands:
            - go get -t -v
    go:test:
        image: golang:1.9
        commands:
            - go test -v -race
        secrets: [ sentry_dsn ]